name: Nightly
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 2 copies
        # of the current job in parallel
        machines: [1, 2]
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          parallel: true
          group: 'Actions example'
          record: true
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}